version: '3.8'
services:
  backend:
    build: ./backend-node   
    ports:
      - "3000:3000"         
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000  